hackolade/Oracle

forward_engineering/ddlProvider.js
forward_engineering/helpers/udtHelper.js

https://hackolade.atlassian.net/browse/HCK-1256

add to script plain type of definitions

---

adapter/0.1.9.json
package.json
properties_pane/entity_level/entityLevelConfig.json
properties_pane/field_level/fieldLevelConfig.json

https://hackolade.atlassian.net/browse/HCK-1255

enforce pk

---

forward_engineering/configs/templates.js
forward_engineering/ddlProvider.js
forward_engineering/helpers/tableHelper.js
properties_pane/model_level/modelLevelConfig.json

https://hackolade.atlassian.net/browse/HCK-1630

add to fk additional properties

---

polyglot/adapter.json
polyglot/convertAdapter.json

Added config for identity derive/convert

HCK 3618 add an ability to convert to and derive from polyglot auto increment property from oracle identity

---

forward_engineering/ddlProvider/ddlHelpers/tableHelper.js
properties_pane/entity_level/entityLevelConfig.json

Fixed issue with invalidly generated ddl of table partitioning in FE

Hck 4088 hackolade re id like to create an oracle partitioned table wit

---

forward_engineering/ddlProvider/ddlHelpers/tableHelper.js
properties_pane/entity_level/entityLevelConfig.json

Added Subpartitions properties field on PP and adjusted dependency config for range_subpartition_descs and list_subpartition_descs. Also fixed a bug with wrong keys used in Subpartition script generation

HCK: adjusted condition for table subpartitions to appear and added Subpartitions description property

---

forward_engineering/ddlProvider/ddlHelpers/viewHelper.js
forward_engineering/ddlProvider/ddlProvider.js

Added fix for invalid tables specification in cross-schema view ddl

HCK-4263: fixed invalid ddl for columns specification in  cross schema view

---

forward_engineering/alterScript/alterScriptFromDeltaHelper.js
forward_engineering/alterScript/alterScriptHelpers/alterEntityHelper.js
forward_engineering/alterScript/alterScriptHelpers/entityHelpers/indexesHelper.js
forward_engineering/alterScript/types/AlterCollectionDto.js
forward_engineering/alterScript/types/AlterIndexDto.js
forward_engineering/ddlProvider/ddlProvider.js
forward_engineering/ddlProvider/templates.js
forward_engineering/utils/general.js

- Added support for ALTER SCRIPT generation for indexes

HCK-4631: add alter script for indexes

---

forward_engineering/ddlProvider/ddlHelpers/sequenceHelper.js
forward_engineering/ddlProvider/ddlProvider.js
forward_engineering/ddlProvider/templates.js
forward_engineering/types/schemaSequenceTypes.js
properties_pane/container_level/containerLevelConfig.json

- Added config for sequences tab on container level
- Implemented schema sequences script generation

Feature/hck 4773  bbva sequences definition for oracle fe of ddl

---

forward_engineering/alterScript/alterScriptFromDeltaHelper.js
forward_engineering/alterScript/alterScriptHelpers/alterEntityHelper.js
forward_engineering/alterScript/alterScriptHelpers/entityHelpers/indexesHelper.js

fixed issue with not generated alter script for newly created index

HCK-5179: Alter script must reflect the creation of an index on a newly created column or newly created table

---

forward_engineering/alterScript/alterScriptHelpers/alterEntityHelper.js

Added properties ids source from role

HCK-5393: When new attribute without index + new index on existing attribute (and no other changes), create index statement is missing

---

forward_engineering/alterScript/alterScriptFromDeltaHelper.js
forward_engineering/alterScript/alterScriptHelpers/alterRelationshipsHelper.js
forward_engineering/alterScript/types/AlterRelationshipDto.js
forward_engineering/ddlProvider/ddlProvider.js
forward_engineering/ddlProvider/templates.js

Added support for relationships Alter Script

Hck 5387 oracle missing alter statement for relationships constraints add and remove

---

forward_engineering/applyToInstanceHelper.js
package-lock.json
package.json
reverse_engineering/api.js
reverse_engineering/helpers/oracleHelper.js

These changes were merged into main https://github.com/hackolade/Oracle/pull/96. This PR was created to avoid merge conflicts between main and plugin-migrate

fix: merge SSH tunneling changes

---

properties_pane/field_level/fieldLevelConfig.json
types/boolean.json
types/object.json

<table>
<td>
<a href="https://hackolade.atlassian.net/browse/HCK-7022" title="HCK-7022" target="_blank"><img alt="Sub-bug" src="https://hackolade.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />HCK-7022</a>  Add support for Boolean type only for Oracle 23ai+
</td></table>
<br />
Added support for Boolean type in Oracle 23ai+
Updated types and PP configs

HCK-7022: added support for Boolean type

---

polyglot/adapter.json
polyglot/convertAdapter.json
properties_pane/field_level/fieldLevelConfig.json
types/boolean.json
types/object.json

<table>
<td>
<a href="https://hackolade.atlassian.net/browse/HCK-7002" title="HCK-7002" target="_blank"><img alt="Production incident" src="https://hackolade.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10564?size=medium" />HCK-7002</a>  [Hackolade] Assignment: Oracle Forward Engineering bugs/features [SEC=OFFICIAL]
</td></table>
<br />
https://hackolade.atlassian.net/browse/HCK-7086
https://hackolade.atlassian.net/browse/HCK-7093
Fixed issues:
1. Added proper conversion from Polyglot integer to Oracle integer as synonym
2. Added Boolean type

Hck 7002 hackolade assignment oracle forward engineering bugs features sec official

---

properties_pane/field_level/fieldLevelConfig.json

<table>
<td>
<a href="https://hackolade.atlassian.net/browse/HCK-7108" title="HCK-7108" target="_blank"><img alt="Sub-task" src="https://hackolade.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10316?size=medium" />HCK-7108</a>  Add flex indication in ERD and DTD
</td></table>
<br />

HCK-7108: add a type decorator for flex column

---

properties_pane/entity_level/entityLevelConfig.json
properties_pane/field_level/fieldLevelConfig.json

<table>
<td>
<a href="https://hackolade.atlassian.net/browse/HCK-6986" title="HCK-6986" target="_blank"><img alt="Sub-task" src="https://hackolade.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10316?size=medium" />HCK-6986</a>  Display type of array item in ERD: first not null: synonym, then subtype, finally type
</td></table>
<br />

HCK-6986: Display synonym in ERD if available

---

forward_engineering/alterScript/alterScriptFromDeltaHelper.js
forward_engineering/alterScript/alterScriptHelpers/alterContainerHelper.js
forward_engineering/alterScript/alterScriptHelpers/alterEntityHelper.js
forward_engineering/alterScript/alterScriptHelpers/alterRelationshipsHelper.js
forward_engineering/alterScript/alterScriptHelpers/alterUdtHelper.js
forward_engineering/alterScript/alterScriptHelpers/alterViewHelper.js
forward_engineering/alterScript/alterScriptHelpers/columnHelpers/alterTypeHelper.js
forward_engineering/alterScript/alterScriptHelpers/columnHelpers/renameColumnHelper.js
forward_engineering/alterScript/alterScriptHelpers/entityHelpers/indexesHelper.js
forward_engineering/config.json
forward_engineering/ddlProvider/ddlHelpers/columnDefinitionHelper.js
forward_engineering/ddlProvider/ddlHelpers/constraintHelper.js
forward_engineering/ddlProvider/ddlHelpers/dualityViewFeHelper/abstractDualityViewDdlCreator.js
forward_engineering/ddlProvider/ddlHelpers/dualityViewFeHelper/dualityViewDdlCreatorFactory.js
forward_engineering/ddlProvider/ddlHelpers/dualityViewFeHelper/sqlDualityViewDdlCreator.js
forward_engineering/ddlProvider/ddlHelpers/indexHelper.js
forward_engineering/ddlProvider/ddlHelpers/synonymHelper.js
forward_engineering/ddlProvider/ddlHelpers/tableHelper.js
forward_engineering/ddlProvider/ddlHelpers/viewHelper.js
forward_engineering/ddlProvider/ddlProvider.js
forward_engineering/utils/general.js

<table>
<td>
<a href="https://hackolade.atlassian.net/browse/HCK-7383" title="HCK-7383" target="_blank"><img alt="Sub-task" src="https://hackolade.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10316?size=medium" />HCK-7383</a>  Add FE script format for quoted and nonquoted object names
</td></table>
<br />
Implemented quoting or not quoting object names according to the chosen script format.
Applied to regular FE and Alter script FE. 
...

HCK-7383 add FE script formats: quoted and nonquoted object names

---

polyglot/adapter.json
types/vector.json

<table>
<td>
<a href="https://hackolade.atlassian.net/browse/HCK-7393" title="HCK-7393" target="_blank"><img alt="Sub-task" src="https://hackolade.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10316?size=medium" />HCK-7393</a>  Derive from Polyglot
</td></table>
<br />

HCK-7393: add a polyglot adapter for vector data type

---

esbuild.package.js
package-lock.json
package.json

<table>
<td>
<a href="https://hackolade.atlassian.net/browse/HCK-7678" title="HCK-7678" target="_blank"><img alt="Sub-task" src="https://hackolade.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10316?size=medium" />HCK-7678</a>  FE script is not generated in browser (Oracle)
</td></table>
<br />

HCK-7678: Make the imports of lodash work in the browser

---

reverse_engineering/connection_settings_modal/connectionSettingsModalConfig.json

Revert "fix: temporarily remove OS dependency"

---

properties_pane/field_level/fieldLevelConfig.json

<table>
<td>
<a href="https://hackolade.atlassian.net/browse/HCK-7711" title="HCK-7711" target="_blank"><img alt="Sub-task" src="https://hackolade.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10316?size=medium" />HCK-7711</a>  Remove old "cleanDependency" property
</td></table>
<br />

HCK-7711: remove old cleanDependency property

---

forward_engineering/ddlProvider/ddlProvider.js
forward_engineering/ddlProvider/templates.js

<table>
<td>
<a href="https://hackolade.atlassian.net/browse/HCK-7729" title="HCK-7729" target="_blank"><img alt="Sub-bug" src="https://hackolade.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />HCK-7729</a>  "insufficient privileges" with newly created schema/tables
</td></table>
<br />
* added "alter session" statement right after creating a schema, to appropriately execute further queries

HCK-7729: insufficient privileges 

---

properties_pane/field_level/fieldLevelConfig.json

<table>
<td>
<a href="https://hackolade.atlassian.net/browse/HCK-7711" title="HCK-7711" target="_blank"><img alt="Sub-task" src="https://hackolade.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10316?size=medium" />HCK-7711</a>  Remove old "cleanDependency" property
</td></table>
<br />
Reverts hackolade/Oracle#120

Revert "HCK-7711: remove old cleanDependency property"

---

forward_engineering/ddlProvider/ddlHelpers/dualityViewFeHelper/sqlDualityViewDdlCreator.js
forward_engineering/ddlProvider/ddlProvider.js
forward_engineering/ddlProvider/templates.js
properties_pane/view_level/viewLevelConfig.json

<table>
<td>
<a href="https://hackolade.atlassian.net/browse/HCK-7741" title="HCK-7741" target="_blank"><img alt="Sub-task" src="https://hackolade.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10316?size=medium" />HCK-7741</a>  Oracle 23ai for Duality Views: add where clause at the root table level
</td></table>
<br />
add where clause at the root table level for Duality View

HCK-7741: Oracle 23ai for Duality Views: add where clause at the root table level

---

types/char.json

Email request. It doesn't need a task

feat: change default char subtype value to varchar2

---

reverse_engineering/connection_settings_modal/connectionSettingsModalConfig.json

Hot fix because I wrongly removed the Service Name choice when connecting using SID.

Fix: wrongly removed dependency between identifier type and service name

---

reverse_engineering/helpers/getSchemaSequences.js

<table>
<td>
<a href="https://hackolade.atlassian.net/browse/HCK-8125" title="HCK-8125" target="_blank"><img alt="Sub-task" src="https://hackolade.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10316?size=medium" />HCK-8125</a>  Add timeout for fetching sequence DDL
</td></table>
<br />

HCK-8125: show warning to the user and skip the process of fetching DDLs of sequences when it takes more than 30s

---

forward_engineering/ddlProvider/ddlHelpers/columnDefinitionHelper.js
forward_engineering/ddlProvider/ddlProvider.js
properties_pane/field_level/fieldLevelConfig.json

<table>
<td>
<a href="https://hackolade.atlassian.net/browse/HCK-8196" title="HCK-8196" target="_blank"><img alt="Sub-task" src="https://hackolade.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10316?size=medium" />HCK-8196</a>  Add ON NULL property in PP and include it in FE
</td></table>
<br />

HCK-8196: add PP config and support for column default on null clause in script 

---

forward_engineering/ddlProvider/ddlProvider.js
forward_engineering/utils/general.js

<table>
<td>
<a href="https://hackolade.atlassian.net/browse/HCK-8608" title="HCK-8608" target="_blank"><img alt="Sub-bug" src="https://hackolade.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />HCK-8608</a>  Oracle. Invalid COMMENT ON statements for Mat. Views in DDL Script tab
</td></table>
<br />
The logic that builds a view comment has been revised.

HCK-8608: Oracle. Invalid COMMENT ON statements for Mat. Views in DDL Script tab

---

types/joinSubquery.json

Fixed type in default values property
...

Fix default subtype value for joinSubQuery type
